#!/bin/bash

DIR=${CODESIGNING_FOLDER_PATH}/../trollbuild
APP=${CODESIGNING_FOLDER_PATH}

function run_at {
    pushd $1
    shift
    $@
    popd
}

codesign --remove "${APP}"
if [ -e "${APP}/_CodeSignature" ]; then
    rm -rf "${APP}/_CodeSignature"
fi
if [ -e "${APP}/embedded.mobileprovision" ]; then
    rm -rf "${APP}/embedded.mobileprovision"
fi

if [ -z "${CODE_SIGN_ENTITLEMENTS}" ]; then
    CODE_SIGN_ENTITLEMENTS=${PROJECT_DIR}/${TARGET_NAME}/${TARGET_NAME}.entitlements
fi

if [ ! -f "${CODE_SIGN_ENTITLEMENTS}" ]; then
    echo "entitlements not exist ${CODE_SIGN_ENTITLEMENTS}, try another"
    CODE_SIGN_ENTITLEMENTS=${PROJECT_DIR}/${TARGET_NAME}.entitlements
    if [ ! -f "${CODE_SIGN_ENTITLEMENTS}" ]; then
        echo "entitlements not exist ${CODE_SIGN_ENTITLEMENTS}, exit"
        exit 1
    fi
fi
echo "use entitlements ${CODE_SIGN_ENTITLEMENTS}"

ldid -S${CODE_SIGN_ENTITLEMENTS} ${APP}/${TARGET_NAME}
rm -rf ${DIR}/${TARGET_NAME}.tipa ${DIR}/Payload
mkdir -p ${DIR}/Payload
cp -rf ${APP} ${DIR}/Payload
run_at ${DIR} "zip -qr ${TARGET_NAME}.tipa Payload"
rm -rf ${DIR}/Payload

IPA_PATH=${DIR}/${TARGET_NAME}.tipa

if [ ! -f ${IPA_PATH} ]; then
    echo "build failed"
    exit -1
fi

if [ ! -z "${TROLLSTORE_DEVICE_IP}" ]; then
    curl -v ${TROLLSTORE_DEVICE_IP}:1222/install/${TARGET_NAME}.tipa -T ${IPA_PATH}
    if [ ! $? -eq 0 ]; then
        echo "install failed"
        exit -1
    fi
fi

exit 0

