#!/bin/bash

chown -R root:wheel /var/jb/Applications/ChargeLimiter.app
chmod +s /var/jb/Applications/ChargeLimiter.app/ChargeLimiterDaemon
killall -9 ChargeLimiter ChargeLimiterDaemon

chown root:wheel /var/jb/Library/LaunchDaemons/chaoge.ChargeLimiter.plist
launchctl load /var/jb/Library/LaunchDaemons/chaoge.ChargeLimiter.plist
uicache mobile

exit 0

