#!/bin/bash

/var/jb/Applications/ChargeLimiter.app/ChargeLimiterDaemon reset
launchctl unload /var/jb/Library/LaunchDaemons/chaoge.ChargeLimiter.plist
killall -9 ChargeLimiter ChargeLimiterDaemon
uicache mobile

exit 0

