#!/bin/bash

/Applications/ChargeLimiter.app/ChargeLimiterDaemon reset
launchctl unload /Library/LaunchDaemons/chaoge.ChargeLimiter.plist
killall -9 ChargeLimiter ChargeLimiterDaemon
uicache mobile

exit 0

