#!/bin/bash

chown -R root:wheel /var/jb/Applications/AlDente.app
chmod +s /var/jb/Applications/AlDente.app/AlDente
killall -9 AlDente

chown root:wheel /var/jb/Library/LaunchDaemons/chaoge.AlDente.plist
launchctl load /var/jb/Library/LaunchDaemons/chaoge.AlDente.plist
uicache mobile

exit 0

