#!/bin/bash

chown -R root:wheel /Applications/AlDente.app
chmod +s /Applications/AlDente.app/AlDente
killall -9 AlDente

chown root:wheel /Library/LaunchDaemons/chaoge.AlDente.plist
launchctl load /Library/LaunchDaemons/chaoge.AlDente.plist
uicache mobile

exit 0

